name: contess
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cmake=3.20.5
  - expat=2.4.1
  - krb5=1.19.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libcxx=11.1.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libssh2=1.9.0
  - libuv=1.41.0
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - ncurses=6.2
  - ninja=1.10.2
  - numexpr=2.7.3
  - numpy=1.21.1
  - openssl=1.1.1k
  - pandas=1.3.1
  - pip=21.1.3
  - pyparsing=2.4.7
  - python=3.8.10
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - readline=8.1
  - rhash=1.4.1
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.36.0
  - svgpathtools=1.4.1
  - svgwrite=1.4.1
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - astroid==2.6.2
    - isort==5.9.2
    - lazy-object-proxy==1.6.0
    - mccabe==0.6.1
    - pylint==2.9.3
    - toml==0.10.2
    - wrapt==1.12.1
